### ISSUE TITLE
Error at example run

### ISSUE THREAD

**Issue by ManosL** [Valish/mma-api#7]
I run these cammands

var mma = require('mma');
var name = process.argv[2] + " " + process.argv[3];
mma.fighter(name, function(data){
	console.log(JSON.stringify(data));
	});

and I get the following error

/home/user/node_modules/request/index.js:44
    throw new Error('undefined is not a valid uri or options object.')
    ^

Error: undefined is not a valid uri or options object.
    at request (/home/user/node_modules/request/index.js:44:11)
    at Object.module.exports.getFighter (/home/user/node_modules/sherdog/lib/sherdog/index.js:16:3)
    at /home/user/node_modules/mma/lib/mma/index.js:105:13
    at Request._callback (/home/user/node_modules/mma/node_modules/google/lib/google.js:85:7)
    at Request.self.callback (/home/user/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/user/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/user/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
 
this might be probably a flaw in the API.

**Comment by valish** [comment]
Looks like an issue with the google search api. You might be accessing it from a weird proxy server that's blocked. Try using the `search-engine-client` npm package in place of the `google` package.
